package com.zyf.autoconfiguredemo;

import com.zyf.entity.School;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@Slf4j
@SpringBootApplication
public class AutoconfigureDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(AutoconfigureDemoApplication.class, args);
    }


    /**
     * 手动装载School覆盖自动配置
     */
    @Bean
    public School school(){
        School school = new School("Generated By Hand",null);
        log.info(school.toString());
        return school;
    }
}
